### ISSUE TITLE
Please, consider to change release policy

### ISSUE THREAD

**Issue by HepoH3** [rejuvenate/lovelace-horizon-card#28]
Hi!
I'm subscribed to this repo, because I'm interested in moon implementation (maybe like others), but now I have mailbox overflowed by notifications about this repo releases.
I really apreciate your work but it's overwhelming and unnecessary.
If one want to be able update card for every change they can just set up hacs to track master branch instead of releases thats all.
Best regards.

**Comment by BerriJ** [comment]
@HepoH3 I agree in part. However, I find the tone of your message completely inappropriate.
We can be thankful that developers have been found to continue this project. And especially at the beginning of a takeover, some things must be tried. 
If it bothers you that much, then fork the project and continue it yourself with the release cycle you deem appropriate.
Otherwise, I suggest you accept how other people work.

**Comment by HepoH3** [comment]
I'm sorry if I hurt someone's feelings, because I really didn't mean to.

**Comment by avataar** [comment]
The way I see it, there are two angles why we do this:
1. We are working hard to get this project in a good state so people can actually use it. Any change should be immediately testable without requiring you to download and build it.
2. Once published to HACS we want to push releases no matter how small a change is.

(1) is mostly the culprit at the moment.

Of course, there are changes (README updates, test code updates, etc) that don't change anything for users, so we should think of a better release strategy in the future.

Regarding "I subscribed to repo X because I'm waiting for Y" it might be better to subscribe just to the particular issue you're interested and not everything that happens.

**Comment by HepoH3** [comment]
> The way I see it, there are two angles why we do this:
> 
>     1. We are working hard to get this project in a good state so people can actually use it. Any change should be immediately testable without requiring you to download and build it.
> 
>     2. Once published to HACS we want to push releases no matter how small a change is.
> 


But the way releases are going now, you force users to test every change have been made no matter of wheter they want it or not (I mean yes, user can skip update, but it's different). I think you're using Semantic versioning scheme, are theese changes are really `minor` release? They look like a `patch` release.
I believe that testing every change should be done by donwloading integration via "main" branch instead of release tag. If someone want to have every change it would be look like these:

![изображение](https://user-images.githubusercontent.com/17159587/227464542-f7586b53-c72e-462e-ac74-234fbd7085a3.png)

Again, I'm sorry if I hurt you.

**Comment by ThomDietrich** [comment]
Hey guys, I agree that the current release pace seems a bit strange, but the project will soon become more stable and we will add distinct features over time. At this point the automatic releases and immediate notification via GitHub and especially on HACS will be beneficial for all users.

> I think you're using Semantic versioning scheme, are these changes are really minor release? They look like a patch release.

This element also bothers me. I believe we should have an option to mark commits to main as non-release-worthy. Be it through the patch version mechanism or another way

**Comment by ThomDietrich** [comment]
I suggest to work with what we have already :)

The project uses https://github.com/rymndhng/release-on-push-action

As per their documentation, I suggest to work with `bump_version_scheme: norelease` in combination with the PR labels `release:major`, `release:minor`, and `release:patch`

**Comment by ThomDietrich** [comment]
I've added all four labels to the project. Someone please feel free to open a PR to (1) change the default setting, and (2) ask users to suggest a severity level of a PR in the PR_TEMPLATE.

Cheers

**Comment by avataar** [comment]
I'm closing this as I believe we got better with not producing a ton of patch releases.
